import { Inter, Syne } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import {NextIntlClientProvider} from 'next-intl';

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const syne = Syne({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getSettings() {
  const response = await fetch(`${process.env.API_BASE_URL}/api/get-public-setting`,{
    cache:"force-cache"
  })
  return response.json()
}

export default async function RootLayout({ children, params }) {
  const settings = await getSettings()
  const {locale} = await params;
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale)) {
    notFound();
  }
  const messages = getMessages();
  return (
    <html lang={locale}>
      <body className={`${syne.variable} ${inter.variable} antialiased`}>
      <NextIntlClientProvider messages={messages}>
        <Navbar />
        {children}
        <Footer settings={settings?.data || {}} />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
